### ISSUE TITLE
IS THERE A Way to make it start witrrh cmus and close when cmus is closed?

### ISSUE THREAD

**Issue by Konpaku-LVX** [Bond-009/cmus-discord-rpc#2]

**Comment by Bond-009** [comment]
You can just run it in the background, it will wait for cmus to start

**Comment by liaminventions** [comment]
@autoteelar 
i have a shell script (music.sh) here that does that:

```
#!/bin/bash
cmus-discord-rpc 2>/dev/null & cmus
```

hope it works for you.
