### ISSUE TITLE
Issue with your README.

### ISSUE THREAD

**Issue by ghost** [Bond-009/cmus-discord-rpc#5]
I find issue with the first part of your README where you state installing rust "on *nix based systems ... should be as simple as installing it from your package manager."

This is a bad way of installing the Rust toolchain due to Rust's 6 week update timescale. `rustup` is a much better way of installing Rust as it is provided by the Rust devs as well as being cross-platform. Packaged versions of Rust from the distro may be out-of-date, packaged in a weird way and require superuser privileges to install while rustup can install the Rust toolchain into the user's home directory.

**Comment by Bond-009** [comment]
I'd be happy to accept a PR that improves the README.
Maybe it should encourage you to install `rustup` from your package manager? (that how I personally installed Rust on my system)
